service: kotlin-lambda-service

provider:
  name: aws
  runtime: java17
  region: us-west-2
  stackTags:
    env: ${opt:stage, 'dev'}
  versionFunctions: false

functions:
  textToSpeech:
    handler: com.example.Handler
    events:
      - http:
          path: mypath
          method: get

package:
  artifact: build/libs/kotlin_serverless_cloud_front.jar

custom:
  stage: ${opt:stage, self:provider.stage}
  awsAccountId: ${aws:accountId}
  awsRegion: ${self:provider.region}

resources:
  Resources:
    MyCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "CloudFront Distribution for my API"
          DefaultRootObject: ''
          Origins:
            - Id: "ApiGatewayOrigin"
              DomainName:
                Fn::Join:
                  - ''
                  - - Ref: ApiGatewayRestApi
                    - '.execute-api.'
                    - Ref: AWS::Region
                    - '.amazonaws.com'
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          DefaultCacheBehavior:
            TargetOriginId: "ApiGatewayOrigin"
            ViewerProtocolPolicy: "redirect-to-https"
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: "202e2ca8-a157-4258-b245-a3f9536b2503" #name=exampleCachePolicyId, it's configured manually
            OriginRequestPolicyId: "e67b8aa6-7453-476e-9d47-e47703f82f49" #name=exampleOriginRequestPolicyId, it's configured manually
          ViewerCertificate:
            CloudFrontDefaultCertificate: true